### PR TITLE
Airport and stops info

### PR DESCRIPTION
**Pull request by lasse-meixner**
Now gives info about the itinerary and number of stops for the cheapest route.

### CODE REVIEW

**Comment by lasse-meixner** [comment]
@uhrzeitranger Finished up from what was left last night.
- Now shows airports and stops for cheapest flights (Re matching sollte jetzt robust sein)
- no longer breaks for me with optional stops.

Mach ruhig auch noch 1/2 test runs und merge wenn es für dich passt.

**Comment by lasse-meixner** [comment]
Would resolve #2

**Review by LBB-at-ETH — COMMENTED** [review]
@lasse-meixner Looks good to me but can you...

- review my pull request first followed by
- stash, pull from master and pop to include my changes and also your variables are called fr, su again bro...

I think this would be the smoothest regarding version control. Correct me if I am wrong.

**Comment by lasse-meixner** [comment]
The smoothest way would just be to merge one branch, pull the new master HEAD into my branch and then go from there. No need to stash.

**Comment by lasse-meixner** [comment]
@uhrzeitranger Since this is working I would merge this first. 
> ... also your variables are called fr, su again bro...

✅ fixed that.

Once the other branch does not throw any more errors I can merge that one, too.

**Pull request merged**
